### ISSUE TITLE
[BUG] 0.20.5 Panic error from `sk --tmux` on early exit (SIGPIPE?)

### ISSUE THREAD

**Issue by wenzel-hoffman** [skim-rs/skim#878]
**Describe the bug**

I see this error if I press Escape (early interruption) before I wait for the full list of options to load:

```
thread '<unnamed>' (645090) panicked at skim/src/tmux.rs:130:54:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It reproduces only with `sk --tmux`, without `--tmux` early exits throw now errors.

**To Reproduce**
1. `find / | sk --tmux`
2. Press Escape before all options are loaded into Skim

**Expected behavior**
No errors thrown, early interruption is part of normal operation.

**Screenshots**
Not relevant.

**Environment (please complete the following information):**
 - OS (`uname -a`): `Linux ... 6.17.9 #1-NixOS SMP PREEMPT_DYNAMIC Mon Nov 24 09:37:52 UTC 2025 x86_64 GNU/Linux`
 - `skim` version (`sk --version`): `sk 0.20.5`
- Shell and version: 
 - Variables (`env | grep '^SKIM'`): `SKIM_DEFAULT_COMMAND=`

**Additional context**
Only `--tmux` is relevant for the bug.

**Comment by LoricAndre** [comment]
This should be fixed in the next release (with ratatui)

**Comment by wenzel-hoffman** [comment]
@LoricAndre is this fixed in 4.0.0? Because for me it still has the same issue, only the error is rendered a bit differently:

````
λ sk --version
sk 4.0.0

λ find / | sk --tmux
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Location: src/tmux.rs:158

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by LoricAndre** [comment]
What do you do to get the panic exactly ? Are you cancelling it with ctrl+c ?

**Comment by wenzel-hoffman** [comment]
@LoricAndre just pressing Escape. But it’s the same behavior if I press Ctrl+C. But even if I select something it’s still showing the same error:
```
λ find / | sk --tmux
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Location: src/tmux.rs:158

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
/boot/efi
```

**Comment by wenzel-hoffman** [comment]
@LoricAndre can we re-open the issue since the bug is still reproducible in the latest release?
